TablaOpcionesCustomizacionRaza = {
	["human"] = {
		["m"] = {
			["complexion"] = 5,
			["face"] = 24,
			["haircolor"] = 48,
			["eyecolor"] = 89,
			["jewelrycolor"] = 5,
			["faceshape"] = 4,
			["mustache"] = 12,
			["earrings"] = 9,
			["piercings"] = 4,
			["eyebrows"] = 17,
			["skincolor"] = 30,
			["gemcolor"] = 10,
			["scars"] = 12,
			["ears"] = 4,
			["necklace"] = 3,
			["sideburns"] = 8,
			["secondaryeyecolor"] = 88,
			["eyetype"] = 4,
			["stubble"] = 13,
			["hairstyle"] = 74,
			["beard"] = 21,
		},
		["f"] = {
			["complexion"] = 5,
			["face"] = 30,
			["haircolor"] = 48,
			["eyecolor"] = 89,
			["jewelrycolor"] = 5,
			["faceshape"] = 3,
			["earrings"] = 11,
			["piercings"] = 7,
			["eyebrows"] = 22,
			["skincolor"] = 30,
			["gemcolor"] = 10,
			["ears"] = 4,
			["necklace"] = 6,
			["makeup"] = 10,
			["eyetype"] = 4,
			["secondaryeyecolor"] = 88,
			["scars"] = 12,
			["hairstyle"] = 70,
		}
	},
	["orc"] = {
		["m"] = {
			["secondaryeyecolor"] = 22,
			["tattoocolor"] = 11,
			["face"] = 9,
			["bodytattoo"] = 13,
			["eyecolor"] = 23,
			["hand(left)"] = 9,
			["faceshape"] = 3,
			["mustache"] = 5,
			["earrings"] = 8,
			["tusks"] = 7,
			["piercings"] = 7,
			["eyebrows"] = 5,
			["haircolor"] = 36,
			["facetattoo"] = 18,
			["skincolor"] = 40,
			["grime"] = 4,
			["sideburns"] = 12,
			["scars"] = 5,
			["ears"] = 2,
			["necklace"] = 8,
			["posture"] = 2,
			["body"] = 7,
			["hand(right)"] = 9,
			["stubble"] = 2,
			["hairstyle"] = 33,
			["beard"] = 18,
		},
		["f"] = {
			["secondaryeyecolor"] = 22,
			["tattoocolor"] = 11,
			["face"] = 9,
			["haircolor"] = 36,
			["eyecolor"] = 23,
			["hand(left)"] = 6,
			["faceshape"] = 2,
			["earrings"] = 17,
			["piercings"] = 5,
			["facetattoo"] = 17,
			["ears"] = 2,
			["necklace"] = 5,
			["skincolor"] = 40,
			["scars"] = 5,
			["hand(right)"] = 6,
			["bodytattoo"] = 13,
			["body"] = 7,
			["hairstyle"] = 45,
		}
	},
	["dwarf"] = {
		["m"] = {
			["secondaryeyecolor"] = 25,
			["tattoocolor"] = 8,
			["garment"] = 3,
			["haircolor"] = 20,
			["eyecolor"] = 26,
			["bodyshape"] = 2,
			["feathercolor"] = 9,
			["faceshape"] = 2,
			["mustache"] = 15,
			["earrings"] = 5,
			["piercings"] = 6,
			["eyebrows"] = 4,
			["feather"] = 7,
			["facetattoo"] = 13,
			["skincolor"] = 29,
			["jewelrycolor"] = 7,
			["face"] = 20,
			["handjewelry"] = 4,
			["bodytattoo"] = 9,
			["hairstyle"] = 27,
			["beard"] = 28,
		},
		["f"] = {
			["piercings"] = 9,
			["eyebrows"] = 18,
			["feather"] = 7,
			["facetattoo"] = 11,
			["tattoocolor"] = 8,
			["face"] = 10,
			["bodytattoo"] = 10,
			["eyecolor"] = 26,
			["skincolor"] = 23,
			["secondaryeyecolor"] = 25,
			["feathercolor"] = 9,
			["jewelrycolor"] = 7,
			["hairstyle"] = 45,
			["haircolor"] = 20,
			["earrings"] = 14,
			["garment"] = 3,
		}
	},
	["nightelf"] = {
		["m"] = {
			["secondaryeyecolor"] = 40,
			["scars"] = 7,
			["haircolor"] = 30,
			["eyecolor"] = 41,
			["blindfold"] = 12,
			["jewelrycolor"] = 14,
			["runes"] = 7,
			["eyebrows"] = 10,
			["gemcolor"] = 14,
			["vinecolor"] = 20,
			["sideburns"] = 7,
			["runescolor"] = 6,
			["beard"] = 17,
			["horns"] = 16,
			["bodyshape"] = 2,
			["vines"] = 2,
			["faceshape"] = 2,
			["mustache"] = 7,
			["hairstyle"] = 45,
			["tattoocolor"] = 11,
			["skincolor"] = 35,
			["headdress"] = 3,
			["face"] = 12,
			["bodytattoo"] = 14,
			["furcolor"] = 30,
			["ears"] = 5,
			["necklace"] = 4,
			["earrings"] = 6,
			["eyetype"] = 2,
			["facetattoo"] = 16,
			["bodytype"] = 2,
		},
		["f"] = {
			["secondaryeyecolor"] = 40,
			["scars"] = 7,
			["haircolor"] = 30,
			["eyecolor"] = 41,
			["blindfold"] = 12,
			["jewelrycolor"] = 14,
			["piercings"] = 8,
			["eyebrows"] = 5,
			["gemcolor"] = 14,
			["vinecolor"] = 20,
			["runescolor"] = 6,
			["horns"] = 16,
			["vines"] = 2,
			["faceshape"] = 2,
			["hairstyle"] = 57,
			["tattoocolor"] = 21,
			["skincolor"] = 35,
			["face"] = 9,
			["facetattoo"] = 20,
			["bodytattoo"] = 12,
			["furcolor"] = 30,
			["runes"] = 7,
			["ears"] = 5,
			["necklace"] = 4,
			["earrings"] = 11,
			["headdress"] = 4,
			["eyetype"] = 2,
			["bodytype"] = 2,
		}
	},
	["undead"] = {
		["m"] = {
			["leg(left)"] = 2,
			["secondaryeyecolor"] = 20,
			["hairgradient"] = 13,
			["facetype"] = 11,
			["eyecolor"] = 20,
			["facefeatures"] = 5,
			["mustache"] = 6,
			["hairstyle"] = 41,
			["arm(right)"] = 2,
			["skincolor"] = 12,
			["arm(left)"] = 2,
			["ribs"] = 4,
			["spine"] = 2,
			["ears"] = 2,
			["sideburns"] = 6,
			["skintype"] = 3,
			["eyebrows"] = 3,
			["leg(right)"] = 2,
			["haircolor"] = 17,
			["face"] = 11,
			["beard"] = 8,
		},
		["f"] = {
			["leg(left)"] = 2,
			["hips"] = 4,
			["hairgradient"] = 13,
			["haircolor"] = 17,
			["eyecolor"] = 20,
			["facefeatures"] = 4,
			["earrings"] = 2,
			["piercings"] = 15,
			["arm(right)"] = 2,
			["skincolor"] = 12,
			["arm(left)"] = 2,
			["spine"] = 2,
			["ears"] = 2,
			["necklace"] = 7,
			["skintype"] = 3,
			["secondaryeyecolor"] = 20,
			["leg(right)"] = 2,
			["face"] = 10,
			["facetype"] = 5,
			["hairstyle"] = 47,
		}
	},
	["tauren"] = {
		["m"] = {
			["mane"] = 5,
			["secondaryeyecolor"] = 17,
			["tail"] = 4,
			["eyecolor"] = 18,
			["jewelrycolor"] = 8,
			["accentcolor"] = 18,
			["gemcolor"] = 8,
			["sideburns"] = 6,
			["facepaint"] = 9,
			["beard"] = 12,
			["hornmarkings"] = 3,
			["goatee"] = 9,
			["nosering"] = 9,
			["flower"] = 2,
			["paintcolor"] = 21,
			["hornstyle"] = 20,
			["earrings"] = 12,
			["headdress"] = 3,
			["taildecoration"] = 4,
			["horncolor"] = 16,
			["face"] = 5,
			["skincolor"] = 35,
			["necklace"] = 3,
			["hair"] = 12,
			["horndecoration"] = 8,
			["foremane"] = 12,
			["bodypaint"] = 8,
		},
		["f"] = {
			["mane"] = 2,
			["hornmarkings"] = 3,
			["secondaryeyecolor"] = 17,
			["face"] = 4,
			["eyecolor"] = 18,
			["flower"] = 2,
			["paintcolor"] = 21,
			["jewelrycolor"] = 8,
			["accentcolor"] = 18,
			["hornstyle"] = 20,
			["earrings"] = 8,
			["taildecoration"] = 5,
			["tail"] = 3,
			["skincolor"] = 27,
			["nosering"] = 12,
			["headdress"] = 3,
			["hairdecoration"] = 6,
			["gemcolor"] = 8,
			["horncolor"] = 16,
			["necklace"] = 8,
			["hair"] = 24,
			["foremane"] = 11,
			["facepaint"] = 9,
			["bodypaint"] = 8,
		}
	},
	["gnome"] = {
		["m"] = {
			["wristjewelry"] = 2,
			["goggles"] = 2,
			["face"] = 7,
			["haircolor"] = 74,
			["eyecolor"] = 32,
			["jewelrycolor"] = 5,
			["accentcolor"] = 7,
			["mustache"] = 24,
			["earrings"] = 12,
			["piercings"] = 5,
			["eyebrows"] = 13,
			["skincolor"] = 23,
			["ears"] = 3,
			["sideburns"] = 6,
			["secondaryeyecolor"] = 31,
			["scars"] = 7,
			["hairgradient"] = 20,
			["hairstyle"] = 63,
			["hairstreaks"] = 75,
			["beard"] = 13,
		},
		["f"] = {
			["wristjewelry"] = 2,
			["goggles"] = 2,
			["hairgradient"] = 20,
			["haircolor"] = 74,
			["eyecolor"] = 32,
			["jewelrycolor"] = 5,
			["accentcolor"] = 7,
			["earrings"] = 22,
			["piercings"] = 8,
			["eyebrows"] = 19,
			["skincolor"] = 23,
			["ears"] = 3,
			["secondaryeyecolor"] = 31,
			["scars"] = 7,
			["face"] = 7,
			["hairaccessory"] = 2,
			["hairstyle"] = 59,
			["hairstreaks"] = 75,
		}
	},
	["troll"] = {
		["m"] = {
			["nosepiercing"] = 7,
			["secondaryeyecolor"] = 23,
			["hairgradient"] = 11,
			["haircolor"] = 43,
			["eyecolor"] = 24,
			["jewelrycolor"] = 12,
			["accentcolor"] = 27,
			["bandages"] = 9,
			["eyebrows"] = 2,
			["sideburns"] = 7,
			["mouthpiercing"] = 4,
			["leg(right)"] = 18,
			["beard"] = 18,
			["hairhighlight"] = 36,
			["tattoostyle"] = 3,
			["mustache"] = 4,
			["hairstyle"] = 39,
			["arm(right)"] = 20,
			["tusks"] = 17,
			["facetattoo"] = 14,
			["arm(left)"] = 20,
			["tuskdecoration"] = 11,
			["leg(left)"] = 18,
			["necklace"] = 5,
			["tattoocolor"] = 43,
			["face"] = 5,
			["bodytattoo"] = 9,
			["skincolor"] = 36,
			["earrings"] = 11,
		},
		["f"] = {
			["leg(left)"] = 25,
			["tusks"] = 10,
			["secondaryeyecolor"] = 23,
			["face"] = 6,
			["bodytattoo"] = 10,
			["eyecolor"] = 24,
			["tattoocolor"] = 43,
			["tattoostyle"] = 3,
			["jewelrycolor"] = 12,
			["accentcolor"] = 27,
			["skincolor"] = 36,
			["nosepiercing"] = 5,
			["bandages"] = 9,
			["hairstyle"] = 54,
			["hairhighlight"] = 33,
			["arm(right)"] = 24,
			["facetattoo"] = 11,
			["arm(left)"] = 24,
			["haircolor"] = 43,
			["browpiercing"] = 4,
			["headdress"] = 3,
			["necklace"] = 9,
			["mouthpiercing"] = 4,
			["hairgradient"] = 11,
			["leg(right)"] = 25,
			["earrings"] = 12,
		}
	},
	["goblin"] = {
		["m"] = {
			["secondaryeyecolor"] = 24,
			["face"] = 7,
			["haircolor"] = 68,
			["eyecolor"] = 25,
			["jewelrycolor"] = 8,
			["nose"] = 11,
			["mustache"] = 9,
			["earrings"] = 9,
			["eyebrows"] = 2,
			["skincolor"] = 20,
			["ears"] = 10,
			["sideburns"] = 8,
			["chin"] = 6,
			["nosering"] = 5,
			["hairgradient"] = 20,
			["hairstyle"] = 50,
			["beard"] = 12,
		},
		["f"] = {
			["skincolor"] = 16,
			["eyebrows"] = 20,
			["nosering"] = 9,
			["secondaryeyecolor"] = 24,
			["hairgradient"] = 20,
			["face"] = 10,
			["haircolor"] = 68,
			["eyecolor"] = 25,
			["bodyshape"] = 2,
			["necklace"] = 7,
			["jewelrycolor"] = 8,
			["hairstyle"] = 48,
			["nose"] = 9,
			["ears"] = 7,
			["earrings"] = 13,
			["chin"] = 7,
		}
	},
	["bloodelf"] = {
		["m"] = {
			["secondaryeyecolor"] = 40,
			["tattoocolor"] = 10,
			["face"] = 12,
			["bodytattoo"] = 17,
			["eyecolor"] = 41,
			["blindfold"] = 12,
			["jewelrycolor"] = 3,
			["accentcolor"] = 5,
			["faceshape"] = 2,
			["mustache"] = 7,
			["earrings"] = 6,
			["runes"] = 12,
			["eyebrows"] = 4,
			["hairgradient"] = 18,
			["facetattoo"] = 22,
			["skincolor"] = 34,
			["gemcolor"] = 6,
			["sideburns"] = 5,
			["horns"] = 7,
			["ears"] = 4,
			["runecolor"] = 6,
			["headdress"] = 3,
			["hairstyle"] = 54,
			["eyetype"] = 2,
			["stubble"] = 2,
			["haircolor"] = 40,
			["beard"] = 23,
		},
		["f"] = {
			["armbands"] = 4,
			["secondaryeyecolor"] = 40,
			["tattoocolor"] = 10,
			["face"] = 12,
			["bodytattoo"] = 17,
			["eyecolor"] = 41,
			["blindfold"] = 12,
			["jewelrycolor"] = 3,
			["accentcolor"] = 5,
			["faceshape"] = 2,
			["earrings"] = 14,
			["runes"] = 12,
			["headdress"] = 3,
			["gemcolor"] = 6,
			["skincolor"] = 33,
			["hairgradient"] = 18,
			["ears"] = 4,
			["necklace"] = 5,
			["horns"] = 7,
			["bracelets"] = 6,
			["eyetype"] = 2,
			["runescolor"] = 6,
			["hairstyle"] = 63,
			["haircolor"] = 40,
		}
	},
	["draenei"] = {
		["m"] = {
			["secondaryeyecolor"] = 28,
			["face"] = 10,
			["haircolor"] = 52,
			["eyecolor"] = 28,
			["bodyshape"] = 3,
			["jewelrycolor"] = 10,
			["faceshape"] = 2,
			["mustache"] = 10,
			["earrings"] = 12,
			["eyebrows"] = 3,
			["headdress"] = 7,
			["trims"] = 2,
			["gemcolor"] = 6,
			["skincolor"] = 24,
			["tail"] = 2,
			["horns"] = 28,
			["necklace"] = 2,
			["tendrils"] = 11,
			["sideburns"] = 12,
			["horndecoration"] = 6,
			["stubble"] = 5,
			["hairstyle"] = 34,
			["beard"] = 17,
		},
		["f"] = {
			["secondaryeyecolor"] = 28,
			["horns"] = 19,
			["haircolor"] = 52,
			["eyecolor"] = 28,
			["facetendrils"] = 4,
			["hairdecoration"] = 2,
			["earrings"] = 6,
			["hornaccessories"] = 28,
			["headdress"] = 12,
			["gemcolor"] = 6,
			["face"] = 10,
			["necklace"] = 3,
			["tendrils"] = 4,
			["tail"] = 6,
			["skincolor"] = 22,
			["trims"] = 2,
			["jewelrycolor"] = 10,
			["hairstyle"] = 36,
		}
	},
	["worgen"] = {
		["m"] = {
			["mane"] = 4,
			["secondaryeyecolor"] = 22,
			["face"] = 7,
			["eyecolor"] = 23,
			["claws"] = 2,
			["faceshape"] = 2,
			["earstyle"] = 18,
			["bodyfur"] = 4,
			["secondaryearstyle"] = 19,
			["tail"] = 5,
			["hairstyle"] = 11,
			["sideburns"] = 12,
			["furcolor"] = 15,
			["fangs"] = 2,
			["foremane"] = 10,
			["beard"] = 12,
		},
		["f"] = {
			["mane"] = 3,
			["secondaryeyecolor"] = 22,
			["face"] = 16,
			["eyecolor"] = 23,
			["claws"] = 2,
			["faceshape"] = 2,
			["earstyle"] = 20,
			["hairaccents"] = 3,
			["secondaryearstyle"] = 21,
			["tail"] = 6,
			["hairstyle"] = 16,
			["bodyfur"] = 4,
			["fangs"] = 2,
			["furcolor"] = 19,
			["foremane"] = 11,
		}
	},
	["gilnean"] = {
		["m"] = {
			["Face"] = 19,
			["FacialHair"] = 9,
			["Haircolor"] = 6,
			["Hairstyle"] = 17,
			["Skincolor"] = 9,
		},
		["f"] = {
			["Face"] = 32,
			["Haircolor"] = 6,
			["Hairstyle"] = 28,
			["Piercings"] = 7,
			["Skincolor"] = 13,
		}
	},
	["pandaren"] = {
		["m"] = {
			["skincolor"] = 18,
			["eyebrows"] = 5,
			["mustache"] = 7,
			["secondaryeyecolor"] = 19,
			["eyecolor"] = 20,
			["face"] = 21,
			["hairstyle"] = 22,
			["beard"] = 20,
		},
		["f"] = {
			["tail"] = 2,
			["skincolor"] = 18,
			["hairstyle"] = 20,
			["secondaryeyecolor"] = 19,
			["haircolor"] = 16,
			["face"] = 20,
			["earrings"] = 6,
			["eyecolor"] = 19,
		}
	},
	["nightborne"] = {
		["m"] = {
			["jawjewelry"] = 5,
			["secondaryeyecolor"] = 21,
			["facejewelry"] = 4,
			["bodytattoo"] = 7,
			["eyecolor"] = 22,
			["jewelrycolor"] = 3,
			["eyeshape"] = 2,
			["mustache"] = 4,
			["earrings"] = 7,
			["eyebrows"] = 3,
			["headdress"] = 2,
			["skincolor"] = 11,
			["face"] = 14,
			["facetattoo"] = 9,
			["haircolor"] = 11,
			["luminoushands"] = 2,
			["hairstyle"] = 16,
			["chinjewelry"] = 5,
			["beard"] = 4,
		},
		["f"] = {
			["jawjewelry"] = 2,
			["secondaryeyecolor"] = 21,
			["facejewelry"] = 5,
			["bodytattoo"] = 7,
			["eyecolor"] = 22,
			["jewelrycolor"] = 3,
			["hairdecoration"] = 2,
			["eyeshape"] = 2,
			["earrings"] = 8,
			["eyebrows"] = 3,
			["headdress"] = 2,
			["skincolor"] = 11,
			["necklace"] = 4,
			["haircolor"] = 11,
			["facetattoo"] = 9,
			["luminoushands"] = 2,
			["face"] = 12,
			["hairstyle"] = 16,
			["chinjewelry"] = 4,
		}
	},
	["highmountain"] = {
		["m"] = {
			["nosepiercing"] = 5,
			["hornmarkings"] = 2,
			["secondaryeyecolor"] = 17,
			["face"] = 5,
			["eyecolor"] = 18,
			["hornwraps"] = 3,
			["hornstyle"] = 9,
			["taildecoration"] = 4,
			["tail"] = 3,
			["skincolor"] = 10,
			["feather"] = 3,
			["headdress"] = 3,
			["bodypaint"] = 4,
			["horncolor"] = 4,
			["bodypaintcolor"] = 3,
			["hair"] = 9,
			["foremane"] = 8,
			["facepaint"] = 4,
			["horndecoration"] = 8,
			["beard"] = 9,
		},
		["f"] = {
			["nosepiercing"] = 4,
			["hornmarkings"] = 2,
			["secondaryeyecolor"] = 17,
			["face"] = 4,
			["eyecolor"] = 18,
			["hornwraps"] = 2,
			["hairdecoration"] = 4,
			["hornstyle"] = 8,
			["earrings"] = 5,
			["taildecoration"] = 5,
			["tail"] = 2,
			["skincolor"] = 10,
			["feather"] = 2,
			["headdress"] = 3,
			["facepaint"] = 4,
			["foremane"] = 7,
			["horncolor"] = 4,
			["necklace"] = 4,
			["bodypaintcolor"] = 3,
			["hair"] = 9,
			["horndecoration"] = 2,
			["bodypaint"] = 4,
		}
	},
	["voidelf"] = {
		["m"] = {
			["secondaryeyecolor"] = 19,
			["bodymarkings"] = 3,
			["face"] = 12,
			["haircolor"] = 40,
			["eyecolor"] = 20,
			["ears"] = 3,
			["facialhair"] = 8,
			["tentacles"] = 2,
			["skincolor"] = 29,
			["stubble"] = 2,
			["hairstyle"] = 13,
			["facemarkings"] = 11,
		},
		["f"] = {
			["secondaryeyecolor"] = 19,
			["bodymarkings"] = 3,
			["face"] = 12,
			["haircolor"] = 40,
			["eyecolor"] = 20,
			["ears"] = 3,
			["facemarkings"] = 11,
			["tentacles"] = 2,
			["skincolor"] = 29,
			["earrings"] = 5,
			["hairstyle"] = 11,
		}
	},
	["lightforged"] = {
		["m"] = {
			["facerune"] = 6,
			["eyebrows"] = 2,
			["skincolor"] = 7,
			["face"] = 10,
			["haircolor"] = 10,
			["eyecolor"] = 4,
			["facialhair"] = 12,
			["jewelrycolor"] = 13,
			["bodyrune"] = 4,
			["horndecoration"] = 4,
			["tendrils"] = 7,
			["hairstyle"] = 13,
			["tail"] = 2,
		},
		["f"] = {
			["horns"] = 13,
			["haircolor"] = 10,
			["eyecolor"] = 4,
			["jewelrycolor"] = 13,
			["hairdecoration"] = 4,
			["earrings"] = 3,
			["facerune"] = 6,
			["headdress"] = 5,
			["skincolor"] = 7,
			["tail"] = 6,
			["jawdecoration"] = 2,
			["tendrils"] = 2,
			["bodyrune"] = 4,
			["horndecoration"] = 7,
			["necklace"] = 2,
			["face"] = 10,
			["hairstyle"] = 13,
		}
	},
	["zandalari"] = {
		["m"] = {
			["secondaryeyecolor"] = 7,
			["haircolor"] = 6,
			["eyecolor"] = 9,
			["hairstyle"] = 12,
			["piercings"] = 6,
			["skincolor"] = 6,
			["tusks"] = 7,
			["tattoocolor"] = 8,
			["eargauge"] = 3,
			["face"] = 6,
			["tattoo"] = 4,

		},
		["f"] = {
			["secondaryeyecolor"] = 7,
			["haircolor"] = 6,
			["eyecolor"] = 9,
			["earrings"] = 2,
			["piercings"] = 4,
			["skincolor"] = 6,
			["tusks"] = 7,
			["tattoocolor"] = 8,
			["necklace"] = 2,
			["tattoo"] = 5,
			["eargauge"] = 3,
			["face"] = 6,
			["hairstyle"] = 10,
		}
	},
	["kultiran"] = {
		["m"] = {
			["secondaryeyecolor"] = 28,
			["face"] = 7,
			["bodytattoo"] = 6,
			["eyecolor"] = 29,
			["mustache"] = 4,
			["hairstyle"] = 6,
			["skincolor"] = 20,
			["sideburns"] = 2,
			["tattoocolor"] = 8,
			["haircolor"] = 48,
			["beard"] = 4,
		},
		["f"] = {
			["secondaryeyecolor"] = 28,
			["haircolor"] = 49,
			["eyecolor"] = 29,
			["earrings"] = 7,
			["eyebrows"] = 2,
			["skincolor"] = 20,
			["necklace"] = 7,
			["tattoocolor"] = 8,
			["face"] = 7,
			["bodytattoo"] = 6,
			["hairstyle"] = 10,
		}
	},
	["thinhuman"] = {
		["m"] = {
			["hairstyle"] = 4,
			["facialhair"] = 7,
			["haircolor"] = 4,
			["skincolor"] = 4,
		},
		["f"] = {

		}
	},
	["darkiron"] = {
		["m"] = {
			["piercings"] = 6,
			["facialhair"] = 7,
			["tattoo"] = 6,
			["skincolor"] = 5,
			["hairstyle"] = 8,
			["face"] = 10,
			["haircolor"] = 6,
			["eyecolor"] = 4,
		},
		["f"] = {
			["piercings"] = 7,
			["tattoo"] = 6,
			["skincolor"] = 5,
			["hairstyle"] = 11,
			["face"] = 10,
			["haircolor"] = 6,
			["eyecolor"] = 4,
		}
	},
	["vulpera"] = {
		["m"] = {
			["pattern"] = 3,
			["secondaryeyecolor"] = 23,
			["face"] = 6,
			["patterncolor"] = 8,
			["eyecolor"] = 24,
			["ears"] = 6,
			["furcolor"] = 9,
			["snout"] = 6,
			["earrings"] = 2,
		},
		["f"] = {
			["pattern"] = 3,
			["secondaryeyecolor"] = 23,
			["face"] = 6,
			["patterncolor"] = 8,
			["eyecolor"] = 24,
			["ears"] = 8,
			["furcolor"] = 9,
			["snout"] = 6,
			["earrings"] = 2,
		}
	},
	["maghar"] = {
		["m"] = {
			["secondaryeyecolor"] = 19,
			["tattoocolor"] = 11,
			["face"] = 9,
			["haircolor"] = 36,
			["eyecolor"] = 20,
			["hand(left)"] = 8,
			["faceshape"] = 3,
			["mustache"] = 5,
			["earrings"] = 6,
			["piercings"] = 7,
			["eyebrows"] = 5,
			["facetattoo"] = 18,
			["bodypiercings"] = 2,
			["grime"] = 4,
			["tusks"] = 5,
			["skincolor"] = 15,
			["sideburns"] = 12,
			["necklace"] = 7,
			["scars"] = 5,
			["posture"] = 2,
			["hand(right)"] = 8,
			["hairstyle"] = 33,
			["bodytattoo"] = 13,
			["beard"] = 18,
		},
		["f"] = {
			["piercings"] = 4,
			["tattoocolor"] = 11,
			["skincolor"] = 15,
			["facetattoo"] = 17,
			["bodypiercings"] = 2,
			["face"] = 9,
			["bodytattoo"] = 13,
			["eyecolor"] = 20,
			["secondaryeyecolor"] = 19,
			["necklace"] = 5,
			["hand(left)"] = 6,
			["hand(right)"] = 6,
			["faceshape"] = 2,
			["hairstyle"] = 46,
			["earrings"] = 17,
			["haircolor"] = 36,
		}
	},
	["mechagnome"] = {
		["m"] = {
			["leg(left)"] = 4,
			["secondaryeyecolor"] = 32,
			["chestmodification"] = 4,
			["hairgradient"] = 20,
			["haircolor"] = 74,
			["eyecolor"] = 32,
			["paintcolor"] = 45,
			["arm(right"] = 9,
			["mustache"] = 24,
			["hairstreaks"] = 75,
			["facemodification"] = 17,
			["optics"] = 9,
			["eyebrows"] = 13,
			["chinmodification"] = 2,
			["skincolor"] = 23,
			["arm(left)"] = 9,
			["sideburns"] = 6,
			["scars"] = 10,
			["face"] = 7,
			["leg(right)"] = 4,
			["earmodification"] = 8,
			["hairstyle"] = 62,
			["beard"] = 13,
		},
		["f"] = {
			["leg(left)"] = 4,
			["secondaryeyecolor"] = 32,
			["chestmodification"] = 4,
			["hairgradient"] = 20,
			["haircolor"] = 74,
			["eyecolor"] = 32,
			["paintcolor"] = 45,
			["hairstreaks"] = 75,
			["facemodification"] = 18,
			["optics"] = 9,
			["arm(right)"] = 9,
			["chinmodification"] = 2,
			["skincolor"] = 23,
			["arm(left)"] = 9,
			["scars"] = 10,
			["eyebrows"] = 19,
			["leg(right)"] = 4,
			["earmodification"] = 8,
			["face"] = 7,
			["hairstyle"] = 59,
		}
	},
	["felorc"] = {
		["m"] = {
			["skincolor"] = 3,
		},
		["f"] = {}
	},
	["naga"] = {
		["m"] = {
			["skincolor"] = 6
		},
		["f"] = {
			["skincolor"] = 6
		}
	},
	["broken"] = {
		["m"] = {
			["haircolor"] = 10,
			["hairstyle"] = 3,
			["skincolor"] = 6,
		},
		["f"] = {

		}
	},
	["skeleton"] = {
		["m"] = {

		},
		["f"] = {

		}
	},
	["vrykul"] = {
		["m"] = {
			["facialhair"] = 6,
			["haircolor"] = 5,
			["hairstyle"] = 6,
			["skincolor"] = 6
		},
		["f"] = {

		}
	},
	["tuskarr"] = {
		["m"] = {
			["facialhair"] = 7,
			["haircolor"] = 7,
			["hairstyle"] = 7,
			["skincolor"] = 7,
		},
		["f"] = {

		}
	},
	["foresttroll"] = {
		["m"] = {
			["face"] = 5,
			["facialhair"] = 11,
			["haircolor"] = 10,
			["hairstyle"] = 6,
			["skincolor"] = 15
		},
		["f"] = {

		}
	},
	["taunka"] = {
		["m"] = {
			["facialhair"] = 3,
			["skincolor"] = 4
		},
		["f"] = {

		}
	},
	["northrendskeleton"] = {
		["m"] = {
			["facialhair"] = 5,
			["haircolor"] = 4,
			["skincolor"] = 4
		},
		["f"] = {

		}
	},
	["icetroll"] = {
		["m"] = {
			["facialhair"] = 5,
			["haircolor"] = 6,
			["hairstyle"] = 6,
			["skincolor"] = 8
		},
		["f"] = {

		}
	},
}